version: "3"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    command: 
      - "--storage.tsdb.retention.time=60d"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

    command: 
      - "--config.file=/etc/alertmanager/alertmanager.yml"


  telegram-warn:
    container_name: telegram-warn
    image: telegram-warn
    ports:
      - "9119:9119"
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml


  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
