global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.17.0.1:9093
rule_files:
- rules/*.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 172.17.0.1:9090
    labels:
      instance: prometheus
- job_name: node
  static_configs:
  - targets:
    - 172.17.0.1:9100
    labels:
      tag:   TAG_FLAG

- job_name: tcp_check
  scrape_interval: 10s
  metrics_path: /probe
  params:
    module:
    - tcp_connect
  static_configs:
  - targets: []
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: 172.17.0.1:9115
